version: '3'

services:
    wpdev:
        image: wpdev:latest
        build: 
          context: ./src
          dockerfile: Dockerfile
        ports:
          - ${IP}:80:80 # change ip if required
        volumes:
          - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
          - ./wp-app:/var/www/html # Full wordpress project
          #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
          #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
        environment:
          WORDPRESS_DB_HOST: "${DB_HOST}"
          WORDPRESS_DB_NAME: "${DB_NAME}"
          WORDPRESS_DB_USER: "${DB_USER}"
          WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
          WP_DEBUG: "${WP_DEBUG}"
          WP_DEBUG_LOG: "${WP_DEBUG_LOG}"
        depends_on:
          - db
        links:
          - db

    wpcli:
        image: wordpress:cli
        user: 1000:1000
        volumes:
          - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
          - ./wp-app:/var/www/html
        environment:
          WORDPRESS_DB_HOST:  "${DB_HOST}"
          WORDPRESS_DB_NAME: "${DB_NAME}"
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
        depends_on:
          - db
          - wpdev
    pma:
      image: phpmyadmin/phpmyadmin
      environment:
        # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
        PMA_HOST: db
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      ports:
        - ${IP}:8080:80
      links:
        - db:db

    db:
      image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
      ports:
        - ${IP}:3306:3306 # change ip if required
      command: [
          '--default_authentication_plugin=mysql_native_password',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci'
      ]
      volumes:
        - ./wp-data:/docker-entrypoint-initdb.d
        - ./db_data:/var/lib/mysql
      environment:
        MYSQL_DATABASE: "${DB_NAME}"
        MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

volumes:
  db_data:
